v5.9.3

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,17 +1,17 @@
 #!/bin/bash
 if [ ! $(command -v wget) ]; then
     echo "please install wget"
-    exit 0
+    exit 1
 fi
 
 if [ ! $(command -v make) ]; then
     echo "please install make"
-    exit 0
+    exit 1
 fi
 
 if [ ! $(command -v vim) ]; then
     echo "please install vim"
-    exit 0
+    exit 1
 fi
 
 if [ -f  /bin/checker ]; then
@@ -30,17 +30,22 @@ if [ -f /tmp/checker/source ]; then
     rm -rf /tmp/checker/source
 fi
 
-echo -e "\e[1;32m[download file] ...\e[0m"
-rm -rf /tmp/checker/source/
-mkdir -p /tmp/checker/source/
-cp -r ./ /tmp/checker/source/
-cd /tmp/checker/source/
+echo -e "\e[32m[copy file] ...\e[0m" && \
+rm -rf /tmp/checker/source/ && \
+mkdir -p /tmp/checker/source/ && \
+cp -r ./ /tmp/checker/source/ && \
+cd /tmp/checker/source/ && \
 
-echo -e "\e[1;32m[compile] ...\e[0m"
-make $1
-echo -e "\e[1;32m[copy file] ...\e[0m"
-sudo sh ./copy.sh
-sudo chmod 777 /usr/local/bin/checker
-mkdir -p /tmp/checker/update
-cp /tmp/checker/source/update.sh /tmp/checker/update/update.sh
+echo -e "\e[32m[compile] ...\e[0m" && \
+make $1 && \
+echo -e "\e[32m[create link] ...\e[0m" && \
+mkdir -p /tmp/checker/update && \
+sudo sh ./copy.sh && \
+sudo chmod 777 /usr/local/bin/checker && \
 sudo chmod 777 /tmp/checker/update/update.sh
+
+ret=$?
+if [ $ret != 0 ]; then
+    echo -e "\n\e[31mshell return $ret, failed.\e[0m"
+fi
+exit $ret
